In [13]:
import pandas as pd
import numpy as np
import glob
import os

In [14]:
df_quality_coffee=pd.read_csv('./coffee.csv')
df_quality_coffee

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
0,United States,kona,0,0,0,2010,kona pacific farmers cooperative,Arabica,NaN,NaN,...,8.42,8.08,7.75,7.67,7.83,10.00,10.00,0.00,86.25,Unknown
1,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,7.92,7.75,8.33,8.00,10.00,10.00,0.08,86.17,Unknown
2,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,8.00,7.75,7.92,8.00,10.00,10.00,0.01,86.17,Unknown
3,Ethiopia,sidamo,0,0,0,2010,ethiopia commodity exchange,Arabica,NaN,NaN,...,8.00,7.83,8.00,7.92,7.83,10.00,10.00,0.00,85.08,Unknown
4,Ethiopia,sidamo,0,0,0,2010,ethiopia commodity exchange,Arabica,NaN,NaN,...,7.83,7.58,8.00,7.83,7.50,10.00,10.00,0.10,83.83,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Guatemala,san marcos,1700,1700,1700,2017,juan luis alvarado romero,Arabica,Bourbon,Washed / Wet,...,7.67,7.42,7.42,7.67,7.67,8.67,8.67,0.10,79.08,Green
985,Honduras,comayagua,1400,1400,1400,2017,bismarck castro,Arabica,Caturra,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0.00,Green
986,India,chikmagalur karnataka indua,3170,3170,3170,2017,nishant gurjer,Robusta,NaN,Washed / Wet,...,7.75,7.92,8.00,7.92,7.92,10.00,8.00,0.00,83.50,Unknown
987,India,chikmagalur karnataka india,3140,3140,3140,2017,nishant gurjer,Robusta,NaN,Washed / Wet,...,7.75,7.83,7.67,7.92,7.83,10.00,7.92,0.10,82.50,Bluish-Green
988,Honduras,western region,1200,1200,1200,2018,mdh,Arabica,Catimor,Washed / Wet,...,7.42,7.08,7.42,7.50,7.33,10.00,10.00,0.11,81.58,Blue-Green

In [15]:
df_quality_coffee["Data.Scores.Total"]== 0

0      False
1      False
2      False
3      False
4      False
       ...
984    False
985     True
986    False
987    False
988    False
Name: Data.Scores.Total, Length: 989, dtype: bool

In [16]:
df_quality_coffee["Data.Scores.Total"].max()

90.58

In [17]:
score_cero= df_quality_coffee[df_quality_coffee['Data.Scores.Total']== 0]
score_cero

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
985,Honduras,comayagua,1400,1400,1400,2017,bismarck castro,Arabica,Caturra,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.12,0.0,Green

In [18]:
df_quality_coffee[df_quality_coffee['Data.Scores.Total']> 89]

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
530,Ethiopia,guji-hambela,1950,2200,2075,2014,metad plc,Arabica,NaN,Washed / Wet,...,8.83,8.67,8.75,8.50,8.42,10.0,10.0,0.12,90.58,Green
531,Ethiopia,guji-hambela,1950,2200,2075,2014,metad plc,Arabica,Other,Washed / Wet,...,8.67,8.50,8.58,8.42,8.42,10.0,10.0,0.12,89.92,Green

In [21]:
df_quality_coffee.describe()

,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Production.Number of bags,Data.Production.Bag weight,Data.Scores.Aroma,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total
count,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000
mean,1640.076845,1675.929221,1657.998989,2013.549039,151.761375,210.491937,7.572831,7.515410,7.387472,7.539697,7.506309,7.500344,9.823893,9.830313,0.093903,81.972133
std,9192.519762,9191.957731,9192.058989,1.658883,125.665490,1666.707294,0.396796,0.420677,0.425284,0.399370,0.391481,0.425055,0.593888,0.691316,0.044666,3.859562
min,0.000000,0.000000,0.000000,2010.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,905.000000,950.000000,950.000000,2012.000000,15.000000,1.000000,7.420000,7.330000,7.250000,7.330000,7.330000,7.330000,10.000000,10.000000,0.100000,81.080000
50%,1300.000000,1310.000000,1300.000000,2013.000000,170.000000,60.000000,7.580000,7.500000,7.420000,7.580000,7.500000,7.500000,10.000000,10.000000,0.110000,82.500000
75%,1550.000000,1600.000000,1600.000000,2015.000000,275.000000,69.000000,7.750000,7.750000,7.580000,7.750000,7.670000,7.750000,10.000000,10.000000,0.120000,83.580000
max,190164.000000,190164.000000,190164.000000,2018.000000,600.000000,19200.000000,8.750000,8.830000,8.670000,8.750000,8.500000,8.580000,10.000000,10.000000,0.280000,90.580000

In [26]:
df_quality_coffee[(df_quality_coffee["Location.Country"]== "Colombia")]

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
25,Colombia,la plata,1600,1950,1775,2011,racafe & cia s.c.a,Arabica,Caturra,Washed / Wet,...,7.67,7.58,7.50,7.67,7.42,10.0,10.0,0.12,83.00,Bluish-Green
28,Colombia,huila,1750,1750,1750,2011,exportadora de cafe condor s.a,Arabica,Caturra,Washed / Wet,...,7.58,7.17,7.58,7.42,7.58,10.0,10.0,0.00,82.42,Green
30,Colombia,huila,1750,1750,1750,2011,exportadora de cafe condor s.a,Arabica,Caturra,Washed / Wet,...,7.42,7.33,7.33,7.50,7.67,10.0,10.0,0.00,81.75,Green
33,Colombia,huila,1750,1750,1750,2011,exportadora de cafe condor s.a,Arabica,Caturra,Natural / Dry,...,7.42,7.25,7.17,7.17,7.75,10.0,10.0,0.11,81.42,Green
52,Colombia,cundinamarca,2136,2136,2136,2012,carcafe ltda ci,Arabica,Caturra,Natural / Dry,...,8.00,7.75,7.75,7.83,7.83,10.0,10.0,0.11,85.08,Green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899,Colombia,la plata,0,0,0,2016,racafe & cia s.c.a,Arabica,NaN,NaN,...,7.75,7.75,7.67,5.25,7.83,10.0,10.0,0.00,81.67,Unknown
901,Colombia,huila,0,0,0,2016,racafe & cia s.c.a,Arabica,Caturra,Washed / Wet,...,7.33,7.33,7.17,7.33,7.42,10.0,10.0,0.00,81.33,Unknown
907,Colombia,guayata,1600,1600,1600,2016,racafe & cia s.c.a,Arabica,Caturra,Washed / Wet,...,7.50,7.42,5.25,7.67,7.75,10.0,10.0,0.00,81.00,Green
935,Colombia,huila,442,442,442,2017,carcafe ltda ci,Arabica,Caturra,Washed / Wet,...,7.83,7.58,7.58,7.58,7.58,10.0,10.0,0.11,83.75,Green
942,Colombia,guayata,1500,1500,1500,2017,racafe & cia s.c.a,Arabica,Caturra,Washed / Wet,...,7.67,7.50,7.33,7.67,7.58,10.0,10.0,0.11,82.92,Green

In [25]:
df_quality_coffee[(df_quality_coffee["Location.Country"]== "Brazil")]

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
1,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,7.92,7.75,8.33,8.00,10.00,10.00,0.08,86.17,Unknown
2,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,8.00,7.75,7.92,8.00,10.00,10.00,0.01,86.17,Unknown
10,Brazil,south of minas,1250,1250,1250,2011,nucoffee,Arabica,Bourbon,Natural / Dry,...,8.50,8.00,8.00,8.00,8.00,10.00,10.00,0.12,86.92,Green
11,Brazil,vale da grama,1300,1300,1300,2011,nucoffee,Arabica,Bourbon,Natural / Dry,...,8.17,8.00,7.75,8.00,8.00,10.00,10.00,0.12,86.42,Green
12,Brazil,south of minas,1250,1250,1250,2011,nucoffee,Arabica,Bourbon,Semi-washed / Semi-pulped,...,8.00,8.00,8.00,7.75,8.00,10.00,10.00,0.11,86.08,Blue-Green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,Brazil,south of minas,944,944,944,2016,ipanema coffees,Arabica,Bourbon,Natural / Dry,...,7.33,7.42,7.50,7.33,7.42,10.00,10.00,0.11,82.00,Green
896,Brazil,monte carmelo,973,973,973,2016,gabriel barbara,Arabica,Mundo Novo,Natural / Dry,...,7.50,7.42,7.50,7.42,7.25,10.00,10.00,0.11,81.83,Green
905,Brazil,alta paulista (sao paulo),695,695,695,2016,gregorio sebba,Arabica,Mundo Novo,Natural / Dry,...,7.42,7.50,7.25,7.75,7.58,9.33,9.33,0.11,81.08,Green
908,Brazil,monte carmelo,0,0,0,2016,bourbon specialty coffees,Arabica,NaN,NaN,...,7.25,7.33,7.08,7.58,7.25,9.33,10.00,0.11,80.58,Green
922,Brazil,campos altos - cerrado,0,0,0,2016,bourbon specialty coffees,Arabica,NaN,NaN,...,6.58,6.58,7.00,7.00,6.42,8.00,10.00,0.11,73.50,Green

### Vasos de 12oz 1.300.000 vasos de agua dar de esta medida